FROM squidfunk/mkdocs-material

RUN pip install --no-cache-dir \
  mkdocs-macros-plugin \
  git+https://github.com/dmitry-radzevich/mkdocs-toc-sidebar-plugin.git


# FUNCIONA MEIA BOCA  
# git+https://github.com/dmitry-radzevich/mkdocs-toc-sidebar-plugin.git

#  git+https://github.com/GlennNZ/mkdocs-toc-sidebar-plugin.git@patch-1#egg=mkdocs-toc-sidebar-plugin

