site_name: Portal de Serviços da SEFAZ Salvador
site_url: https://robazza.github.io/catalogo-sefaz/mkdocs-test1/site/
repo_url: https://github.com/robazza/catalogo-sefaz
edit_uri: tree/master/mkdocs-test1/docs/src/markdown
site_description: |
  A Coordenadoria de Tecnologia da Informação e Comunicação - COT, 
  apresenta o Portal de Processos, com o objetivo de melhorar a qualidade dos produtos desenvolvidos,
  contendo a metodologia de trabalho para nortear a prestação dos seus serviços de forma mais eficaz

copyright: |
  Copyright &copy; 2014 - 2021 <a href="https://github.com/facelessuser"  target="_blank" rel="noopener">Isaac Muse</a>

docs_dir: docs/src/markdown
theme:
  name: material
  custom_dir: docs/theme
  icon:
    logo: material/book-open-page-variant
#  palette:
#    scheme: dracula
#    primary: deep purple
#    accent: deep purple
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
#  icon:
#  logo: icoPPS.png
#  favicon: favicon.png
    
  features:
    - tabs
    - navigation.tabs
    #- navigation.sections
    - navigation.expand

nav:
  - Portal:
    - conheca.md
  - Servicos:
    - servicos/site-100.md
    - servicos/site-101.md
    - servicos/site-102.md
    - servicos/site-103.md
    - servicos/site-115.md
    - servicos/site-117.md
    - servicos/site-118.md
    - servicos/site-119.md
    - servicos/site-133.md
    - servicos/site-134.md
    - servicos/site-135.md
    - servicos/site-15.md
    - servicos/site-151.md
    - servicos/site-153.md
    - servicos/site-154.md
    - servicos/site-16.md
    - servicos/site-161.md
    - servicos/site-18.md
    - servicos/site-186.md
    - servicos/site-194.md
    - servicos/site-197.md
    - servicos/site-20.md
    - servicos/site-41.md
    - servicos/site-45.md
    - servicos/site-91.md
    - servicos/site-92.md
    - servicos/site-93.md
    - servicos/site-94.md
    - servicos/site-98.md
    - servicos/site-99.md
    - idx: servicos/index.md
#  - About:
#    - Contributing &amp; Support: about/contributing.md
#    - Development: about/development.md
#    - Changelog: about/changelog.md
#    - Release Notes:
#        - '6.0': about/releases/6.0.md
#        - '7.0': about/releases/7.0.md
#        - '8.0': about/releases/8.0.md
#    - License: about/license.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: md-render
          class: md-render
#          format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
      - docs/src/markdown/_snippets
      - LICENSE.md
      auto_append:
      - refs.txt
      check_paths: true
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/facelessuser
    - icon: fontawesome/brands/discord
      link: https://discord.gg/TWs8Tgr
extra_css:
  - assets/pymdownx-extras/extra-aa7dff8003.css
  - assets/css/sefaz.css
extra_javascript:
  - assets/pymdownx-extras/extra-uml-51b11a9a.js

plugins:
  - search
  - macros
#  - toc-sidebar
#  - git-revision-date-localized
  - minify:
      minify_html: true
