csv = [
  {
    "Carimbo de data/hora": "18/06/2021 15:53:46",
    "Código Único": "site-15",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Emissão da 2ª via Parcelamento",
    "Nome Popular": "2ª via de Parcelamento",
    "Descrição": "Consiste na emissão de 2ª via de parcelamento municipais",
    "Documentação Exigida": "Numero do parcelamento ou acesso ao site do PAD/PPI com senha do contribuinte",
    "Custo": "Sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos"
  },
  {
    "Carimbo de data/hora": "21/06/2021 11:21:31",
    "Código Único": "site-16",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online, E-mail",
    "Nome do Serviço": "Emissão Demonstrativo da Parte Reconhecida",
    "Nome Popular": "Demonstrativo da Parte Reconhecida",
    "Descrição": "Emissão do demonstrativo de lançamento de débitos após a impugnação",
    "Documentação Exigida": "Inscrição",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/IPTU/EmissaoDemonstrativoParteReconhecida?Length=4"
  },
  {
    "Carimbo de data/hora": "21/06/2021 13:00:19",
    "Código Único": "site-18",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Certidão Positiva com efeitos de Negativa",
    "Nome Popular": "Certidão Positiva com efeitos de Negativa",
    "Descrição": "Emissão de documento certificando que existe débitos do contribuinte, contudo o contribuinte entrou em acordo com a SEFAZ.",
    "Documentação Exigida": "Inscrição Imobiliária ou Municipal (CGA) ou CPF ou CNPJ.",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/imobiliario/Certidao/Pesquisar?funcao=UC00100"
  },
  {
    "Carimbo de data/hora": "21/06/2021 13:22:51",
    "Código Único": "site-19",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Certidão Negativa de Débito",
    "Nome Popular": "CND",
    "Descrição": "Emissão de documento certificando que não existe nenhuma pendência financeira com a SEFAZ até o momento.",
    "Documentação Exigida": "Inscrição Imobiliária ou CPF",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/IPTU/certidaoDebito?Length=4"
  },
  {
    "Carimbo de data/hora": "21/06/2021 14:08:41",
    "Código Único": "site-20",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Validação da Certidão de Débito do Cadastro Imobiliário",
    "Nome Popular": "Validação da Certidão de Débito",
    "Descrição": "Verificar se a certidão emitida é oficial",
    "Documentação Exigida": "Código de Controle da Certidão",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/IPTU/validaCertidaoDebito?Length=4"
  },
  {
    "Carimbo de data/hora": "22/06/2021 10:12:56",
    "Código Único": "site-21",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Presencial, E-mail",
    "Nome do Serviço": "Consulta de Débitos",
    "Nome Popular": "Consulta de Débitos",
    "Descrição": "Verificação se existe débitos em aberto de IPTU/TRSD",
    "Documentação Exigida": "Inscrição Imobiliária ou CPF",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/IPTU/consultaDebito?Length=4"
  },
  {
    "Carimbo de data/hora": "22/06/2021 10:39:59",
    "Código Único": "site-41",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Serviços Parcelamento",
    "Nome Popular": "Parcelamento de Débitos",
    "Descrição": "Consiste em efetuar o parcelamento de débito contido na Prefeitura",
    "Documentação Exigida": "Senha web e inscrição Municipal ou Imobiliária",
    "Custo": "Sem custo",
    "Prazo de Atendimento": "Pronto atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos"
  },
  {
    "Carimbo de data/hora": "22/06/2021 14:02:34",
    "Código Único": "site-42",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Certidão Negativa de Débito TFF",
    "Nome Popular": "CND PJ",
    "Descrição": "Consiste em emitir um documento certificando que não existe débito na SEFAZ.",
    "Documentação Exigida": "Inscrição de CGA ou CNPJ",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/TFF/certidaoDebitoTFF"
  },
  {
    "Carimbo de data/hora": "22/06/2021 15:08:13",
    "Código Único": "site-43",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Presencial",
    "Nome do Serviço": "Consulta de Débitos TFF",
    "Nome Popular": "Consulta de débitos",
    "Descrição": "Consiste em verificar os débitos de TFF.",
    "Documentação Exigida": "Inscrição Municipal (CGA) ou CNPJ",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 e 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/TFF/consultaDebitoTFF"
  },
  {
    "Carimbo de data/hora": "22/06/2021 15:18:48",
    "Código Único": "site-45",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Validação da Certidão de Débito de TFF",
    "Nome Popular": "Validação da Certidão",
    "Descrição": "Verificar se a certidão emitida é oficial",
    "Documentação Exigida": "Código de Controle da Certidão",
    "Custo": "Sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/TFF/validaCertidaoDebito?Length=3"
  },
  {
    "Carimbo de data/hora": "22/06/2021 15:52:18",
    "Código Único": "site-77",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Serviços Parcelamento",
    "Nome Popular": "Adesão ao PAD ou PPI",
    "Descrição": "Adesão ao parcelamento de tributos Municipais  IPTU/TRSD - ISS - TFF - Auto de Infração - NFL, RDT.",
    "Documentação Exigida": "Senha web, inscrição Imobiliária ou Inscrição Municiapal (CGA), CPF ou CNPJ",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos"
  },
  {
    "Carimbo de data/hora": "22/06/2021 16:00:33",
    "Código Único": "site-82",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Certidão Negativa de Débito ISS",
    "Nome Popular": "CND",
    "Descrição": "Consiste na emissão do documento que não existe débito na SEFAZ até o momento.",
    "Documentação Exigida": "Inscrição Municipal (CGA), CPF ou CNPJ",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/ISS/IssCertidaoNegativaDebito"
  },
  {
    "Carimbo de data/hora": "23/06/2021 10:23:51",
    "Código Único": "site-83",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Presencial",
    "Nome do Serviço": "Consulta de Débitos ISS",
    "Nome Popular": "Consulta de Débitos ISS",
    "Descrição": "Consiste em verificação dos débitos de ISS de Autônomo",
    "Documentação Exigida": "Inscrição Municipal (CGA), CPF ou CNPJ.",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/ISS/IssConsultaDebito"
  },
  {
    "Carimbo de data/hora": "23/06/2021 11:20:30",
    "Código Único": "site-91",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "2ª Via de DAM",
    "Nome Popular": "2ª Via de DAM",
    "Descrição": "Consiste em emitir a 2ª via do Documento de Arrecadação Municipal",
    "Documentação Exigida": "1ª via do DAM ou CPF ou CNPJ ou CGA.",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM"
  },
  {
    "Carimbo de data/hora": "23/06/2021 13:29:19",
    "Código Único": "site-92",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Emissão da 2ª Via DAM IPTU/TRSD",
    "Nome Popular": "2ª Via IPTU",
    "Descrição": "Consiste em emitir a 2ª via do Documento de Arrecadação Municipal de IPTU/TRSD",
    "Documentação Exigida": "1ª via do DAM ou CPF ou Inscrição Imobiliária",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Iptu/Emissao2via_iptuTrsd"
  },
  {
    "Carimbo de data/hora": "23/06/2021 13:52:23",
    "Código Único": "site-93",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Emissão da 2ª via TFF",
    "Nome Popular": "2ª via TFF",
    "Descrição": "Consiste em emitir a 2ª via da Taxa de Fiscalização de Funcionamento",
    "Documentação Exigida": "CNPJ ou Inscrição Municipal (CGA)",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/Emissao2viaTFF?Length=3"
  },
  {
    "Carimbo de data/hora": "23/06/2021 14:13:27",
    "Código Único": "site-94",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Emissão da 2ª via ISS/TFF Autônomo",
    "Nome Popular": "2ª via ISS/TFF Autônomo",
    "Descrição": "Consiste em emitir a 2ª via do Imposto Sobre o Serviço do cadastro de Autônomo.",
    "Documentação Exigida": "CPF ou Inscrição Municipal (CGA)",
    "Custo": "Sem Custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/Emissao2viaDamTffAutonomo?Length=3"
  },
  {
    "Carimbo de data/hora": "23/06/2021 15:12:17",
    "Código Único": "site-95",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE",
    "Canal": "Presencial",
    "Nome do Serviço": "Emissão da 2ª via Foro",
    "Nome Popular": "2ª via Foro",
    "Descrição": "Consiste em emitir a 2ª via do Foro",
    "Documentação Exigida": "Não se aplica",
    "Custo": "Sem custo",
    "Prazo de Atendimento": "não se aplica",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/Emissao2viaForo?Length=3"
  },
  {
    "Carimbo de data/hora": "23/06/2021 15:51:20",
    "Código Único": "site-96",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Parcelamentos",
    "Nome Popular": "Parcelamentos PAD/PPI",
    "Descrição": "Consiste em efetuar o parcelamento de débitos da SEFAZ",
    "Documentação Exigida": "senha web, inscrição Municipal (CGA) ou Inscrição Imobiliária",
    "Custo": "Sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 8.422/2013 / Lei 9.548 de 2020 (atualizado)",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos"
  },
  {
    "Carimbo de data/hora": "23/06/2021 15:55:50",
    "Código Único": "site-97",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE",
    "Canal": "Presencial",
    "Nome do Serviço": "Emissão da 2ª via do DAM ISS Declarado",
    "Nome Popular": "Emissão da 2ª via do DAM ISS Declarado",
    "Descrição": "não se aplica",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "não se aplica",
    "Legislação": "LEI Nº 8.421/2013",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/issDeclarado?Length=3"
  },
  {
    "Carimbo de data/hora": "25/06/2021 15:46:08",
    "Código Único": "site-98",
    "Coordenação Responsável": "CFI",
    "Setor Responsável": "",
    "Nome Responsável": "",
    "E-mail Responsável": "",
    "Locais de Atendimento": "Posto Central - SEDE",
    "Canal": "Online, Presencial",
    "Nome do Serviço": "Emissão da 2ª via do DAM ISS Declaracao Economica",
    "Nome Popular": "Emissão da 2ª via do DAM ISS Declaracao Economica",
    "Descrição": "Emissão do ISS Declarado especifico",
    "Documentação Exigida": "CGA, CNPJ, e as compentências",
    "Custo": "",
    "Prazo de Atendimento": "não informado",
    "Legislação": "não informado",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/EmissaoDeclaraEconomica?Length=3"
  },
  {
    "Carimbo de data/hora": "28/06/2021 10:46:16",
    "Código Único": "site-99",
    "Coordenação Responsável": "CFI",
    "Setor Responsável": "SEDOF",
    "Nome Responsável": "",
    "E-mail Responsável": "",
    "Locais de Atendimento": "Posto Central - SEDE",
    "Canal": "Online, Presencial",
    "Nome do Serviço": "Emissão da 2ª via do DAM ISS Substituto Tributário",
    "Nome Popular": "Emissão da 2ª via do DAM ISS Substituto Tributário",
    "Descrição": "Imposto cuja a obrigação é do tomador do serviço",
    "Documentação Exigida": "Inscrição do CGA ou CNPJ",
    "Custo": "",
    "Prazo de Atendimento": "não",
    "Legislação": "LEI nº 8421 de 2013",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/EmissaoDamIssSubsTributario?Length=3"
  },
  {
    "Carimbo de data/hora": "28/06/2021 10:58:59",
    "Código Único": "site-100",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Emissão da 2ª Via DAM IPTU/TRSD em Dívida Ativa",
    "Nome Popular": "Emissão da 2ª Via DAM IPTU/TRSD em Dívida Ativa",
    "Descrição": "Consiste em emissão de 2ª via do IPTU em divida ativa",
    "Documentação Exigida": "Inscrição Imobiliária",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto atendimento",
    "Legislação": "Lei nº 7.186 de 2003",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Iptu/Emissao2via_DividaAtiva"
  },
  {
    "Carimbo de data/hora": "28/06/2021 12:06:22",
    "Código Único": "site-101",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Emissão da 2ª via DAM TFF em Dívida Ativa",
    "Nome Popular": "2ª via DAM TFF em Dívida Ativa",
    "Descrição": "Consiste na emissão da 2ª via da Taxa de Fiscalização e Funcionamento que já consta na Divida Ativa",
    "Documentação Exigida": "Inscrição do CGA ou CNPJ",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/DamTFFDividaAtiva?Length=3"
  },
  {
    "Carimbo de data/hora": "28/06/2021 12:24:40",
    "Código Único": "site-102",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Emissão da 2ª via do DAM ISS Dívida Ativa",
    "Nome Popular": "2ª via do ISS  autônomo Dívida Ativa",
    "Descrição": "Consiste na 2ª do ISS Autônomo que enviado para Divida Ativa",
    "Documentação Exigida": "Inscrição do CGA ou CPF",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto atendimento",
    "Legislação": "LEI nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/DAM/EmissaoDamIssAutonomoDividaAtiva?Length=3"
  },
  {
    "Carimbo de data/hora": "28/06/2021 13:25:13",
    "Código Único": "site-103",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Obter Código p/ Débito Automático",
    "Nome Popular": "Obter Código p/ Débito Automático",
    "Descrição": "Consiste em obter o código para débito automático",
    "Documentação Exigida": "Inscrição Imobiliária ou Inscrição CGA ou nº de parcelamento",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "LEI nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Iptu/Obterdebitoautomatico"
  },
  {
    "Carimbo de data/hora": "28/06/2021 13:53:39",
    "Código Único": "site-115",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Certidões",
    "Nome Popular": "Certidões",
    "Descrição": "Consiste em emissão das certidões da SEFAZ",
    "Documentação Exigida": "Inscrição de CGA ou CPF ou CNPJ ou Inscrição Imobiliária",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "LEI nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Certidoes"
  },
  {
    "Carimbo de data/hora": "29/06/2021 09:30:34",
    "Código Único": "site-116",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Certidão Positiva com efeitos de Negativa e Positiva",
    "Nome Popular": "Certidão Positiva com efeitos de Negativa e Positiva",
    "Descrição": "Consiste em acesso ao e-sefaz para consulta de débitos e emissão de certidão",
    "Documentação Exigida": "Senha web",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/imobiliario/Certidao/Pesquisar?funcao=UC00100"
  },
  {
    "Carimbo de data/hora": "29/06/2021 09:58:12",
    "Código Único": "site-117",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Certidão Negativa de Débitos Imobiliários",
    "Nome Popular": "Certidão Negativa de Débitos Imobiliários",
    "Descrição": "Consiste em emissão de documento certificando que não existe nenhuma pendência financeira com a SEFAZ até o momento.",
    "Documentação Exigida": "Inscrição Imobiliária",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Certidoes/CtdNegaDbtImob?Length=9"
  },
  {
    "Carimbo de data/hora": "29/06/2021 10:15:45",
    "Código Único": "site-118",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's, Postos Prefeitura Bairro",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Certidão Negativa de Débitos Mobiliários",
    "Nome Popular": "Certidão Negativa de Débitos Mobiliários",
    "Descrição": "Consiste em emitir documento certificando que não existe nenhuma pendência financeira com a SEFAZ até o momento.",
    "Documentação Exigida": "Inscrição CGA",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Certidoes/CtdNegaDbtMob?Length=9"
  },
  {
    "Carimbo de data/hora": "29/06/2021 10:40:28",
    "Código Único": "site-119",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online, E-mail",
    "Nome do Serviço": "Consulta Solicitação de Certidão",
    "Nome Popular": "Consulta Solicitação de Certidão",
    "Descrição": "Consiste em consultar a certidão pelo número da solicitação",
    "Documentação Exigida": "Número da Solicitação da certidão",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Certidoes/ConsultaCtd?Length=9"
  },
  {
    "Carimbo de data/hora": "29/06/2021 11:03:20",
    "Código Único": "site-133",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Carta de Anuência e consultar seus débitos",
    "Nome Popular": "Carta de Anuência",
    "Descrição": "Consiste em emitir a carta que corresponde ao protesto referente ao débito tributário",
    "Documentação Exigida": "CPF ou CNPJ ou inscrição Mobiliária ou Inscrição Imobiliária ou nº do AI/NFL/RDT",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/cartaanuencia/Home/PesquisaCartaAnuencia"
  },
  {
    "Carimbo de data/hora": "29/06/2021 11:26:23",
    "Código Único": "site-134",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, E-mail",
    "Nome do Serviço": "Validar uma Carta de Anuência",
    "Nome Popular": "Validar Carta de Anuência",
    "Descrição": "Consiste em verificar a validação da carta de anuência",
    "Documentação Exigida": "Carta de Anuência",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/cartaanuencia/Home/ValidarCartaAnuencia"
  },
  {
    "Carimbo de data/hora": "29/06/2021 11:46:47",
    "Código Único": "site-135",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, E-mail",
    "Nome do Serviço": "Validar uma Carta de Cancelamento",
    "Nome Popular": "Validar uma Carta de Cancelamento",
    "Descrição": "Consiste em verificar se a carta de anuência foi cancelada",
    "Documentação Exigida": "Carta de anuência",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/cartaanuencia/Home/ValidarCartaCancelamento"
  },
  {
    "Carimbo de data/hora": "29/06/2021 12:21:44",
    "Código Único": "site-151",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Formulários",
    "Nome Popular": "Formulários",
    "Descrição": "Impressão dos Formulários para processo e cadastro",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "não se aplica",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Servicos/formularios"
  },
  {
    "Carimbo de data/hora": "29/06/2021 12:30:21",
    "Código Único": "site-153",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Anexo II – Declaração de extravio - Pessoa Física",
    "Nome Popular": "Formulário Declaração de extravio - Pessoa Física",
    "Descrição": "Formulário em PDF do Anexo II da IN SEFAZ/DRM 10/2018",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "IN SEFAZ/DRM 10/2018",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Documento/ObterArquivo/1587"
  },
  {
    "Carimbo de data/hora": "29/06/2021 14:42:08",
    "Código Único": "site-154",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Anexo III - Declaração de extravio - Pessoa Jurídica",
    "Nome Popular": "Formulário Declaração de extravio - PJ",
    "Descrição": "Formulário em PDF do Anexo III da IN SEFAZ/DRM 10/2018",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "IN SEFAZ/DRM 10/2018",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Documento/ObterArquivo/1586"
  },
  {
    "Carimbo de data/hora": "29/06/2021 14:46:52",
    "Código Único": "site-161",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "PETIÇÃO",
    "Nome Popular": "PETIÇÃO",
    "Descrição": "Formulário em PDF para diversas solicitações de abertura de Processo",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Arquivos/Formularios/Peticao.pdf"
  },
  {
    "Carimbo de data/hora": "29/06/2021 14:56:11",
    "Código Único": "site-186",
    "Coordenação Responsável": "CTJ",
    "Setor Responsável": "",
    "Nome Responsável": "",
    "E-mail Responsável": "",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Online, Presencial, E-mail",
    "Nome do Serviço": "Imunidade Tributária/Instituição Filantrópica",
    "Nome Popular": "Imunidade Tributária/Instituição Filantrópica",
    "Descrição": "Processo Administrativo de Débito referente a Imunidade Tributária",
    "Documentação Exigida": "RG, CPF, CNPJ, Contrato Social, Ata e Estatuto, certificado da Instituição Filantrópica.",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Indeterminado",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Servicos/Atendimento"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:06:01",
    "Código Único": "site-194",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SECOP",
    "Nome Responsável": "Alexandre Cezar Cotrim Nery",
    "E-mail Responsável": "anery@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "PARCELAMENTO ADMINISTRATIVO DE DÉBITOS - PAD",
    "Nome Popular": "PAD",
    "Descrição": "Sistema de Parcelamento de Débitos Tributários e Não Tributários",
    "Documentação Exigida": "Cadastro no site (senha web) mediante cadastro débitos aparecerão",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 8.422 de 2013",
    "urlsite": "https://pad.salvador.ba.gov.br/"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:09:30",
    "Código Único": "site-195",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SECOP",
    "Nome Responsável": "Alexandre Cezar Cotrim Nery",
    "E-mail Responsável": "anery@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Parcelamentos",
    "Nome Popular": "Parcelamentos",
    "Descrição": "Acordo de quitação de débitos, pagamento a vista ou parcelado",
    "Documentação Exigida": "Cadastro no site (senha web)",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 8.422/2013, de 15 de julho de 2013",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:12:16",
    "Código Único": "site-196",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SECOP",
    "Nome Responsável": "Alexandre Cezar Cotrim Nery",
    "E-mail Responsável": "anery@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "Informações",
    "Nome Popular": "Informações",
    "Descrição": "Informações",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "não se aplica",
    "Legislação": "Lei nº 8.422/2013, de 15 de julho de 2013",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos/AboutParcelamentos?Length=13"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:15:13",
    "Código Único": "site-197",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SECOP",
    "Nome Responsável": "Alexandre Cezar Cotrim Nery",
    "E-mail Responsável": "anery@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "PPI",
    "Nome Popular": "PPI",
    "Descrição": "Programa de Parcelamento Incentivado, quando em vigor disponibiliza descontos",
    "Documentação Exigida": "cadastro na senha web",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Ultimo em vigor Lei 9.548 de 02 de outubro de 2020",
    "urlsite": "https://ppi.salvador.ba.gov.br/"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:17:54",
    "Código Único": "site-198",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SECOP",
    "Nome Responsável": "Alexandre Cezar Cotrim Nery",
    "E-mail Responsável": "anery@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "",
    "Canal": "Online",
    "Nome do Serviço": "PAD",
    "Nome Popular": "PAD",
    "Descrição": "Acordo de parcelamento administrativo",
    "Documentação Exigida": "Cadastro senha WEB",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 8.422/2013, de 15 de julho de 2013",
    "urlsite": "https://pad.salvador.ba.gov.br/"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:31:58",
    "Código Único": "site-199",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SEATE",
    "Nome Responsável": "Carlos Augusto Silva Santos",
    "E-mail Responsável": "casantos@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE, Postos SAC's",
    "Canal": "Presencial",
    "Nome do Serviço": "Parcelamento SEFAZ",
    "Nome Popular": "Parcelamento SEFAZ",
    "Descrição": "Parcelamento de Débitos pelo sistema SAT (não é mais usado)",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "não se aplica",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos/ParcelamentoSEFAZ?Length=13"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:41:50",
    "Código Único": "site-200",
    "Coordenação Responsável": "PGMS",
    "Setor Responsável": "",
    "Nome Responsável": "",
    "E-mail Responsável": "",
    "Locais de Atendimento": "Posto Central - SEDE",
    "Canal": "Presencial",
    "Nome do Serviço": "Parcelamento Dívida Ativa",
    "Nome Popular": "Parcelamento Dívida Ativa",
    "Descrição": "Parcelamento via sistema exclusivo Divida Ativa",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "não se aplica",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos/ParcelamentoDividaAtiva?Length=13"
  },
  {
    "Carimbo de data/hora": "29/06/2021 15:50:41",
    "Código Único": "site-201",
    "Coordenação Responsável": "CRC",
    "Setor Responsável": "SECOP",
    "Nome Responsável": "Alexandre Cezar Cotrim Nery",
    "E-mail Responsável": "anery@sefaz.salvador.ba.gov.br",
    "Locais de Atendimento": "Posto Central - SEDE",
    "Canal": "Presencial",
    "Nome do Serviço": "Parcelamento REFIS",
    "Nome Popular": "Parcelamento REFIS",
    "Descrição": "Parcelamento com Desconto (PPI)",
    "Documentação Exigida": "não se aplica",
    "Custo": "sem custo",
    "Prazo de Atendimento": "Pronto Atendimento",
    "Legislação": "Lei nº 7.186 de 2006",
    "urlsite": "https://www.sefaz.salvador.ba.gov.br/Parcelamentos/ParcelamentoREFIS?Length=13"
  }
]

console.log(csv)

function genheader(ln) {
	return `---
title: "${ln['Nome do Serviço']}"
descricao: |
 ${ln['Descrição']}
legislação: ${ln['Legislação'].split(',').map(x=>'\n - \''+x+'\'').join('')}
prazo: ${ln['Prazo de Atendimento']}
custo: ${ln['Custo']}
documentacao: ${ln['Documentação Exigida'].split(',').map(x=>'\n - \''+x+'\'').join('')}
responsavel:
  coordenacao: ${ln['Coordenação Responsável']}
  setor: ${ln['Setor Responsável']}
  nome: ${ln['Nome Responsável']}
  email: ${ln['E-mail Responsável']}
canais: ${ln['Canal'].split(', ').map(x=>'\n - \''+x+'\'').join('')}
urlsite: ${ln['urlsite']}
unidades: ${ln['Locais de Atendimento'].split(',').map(x=>'\n - '+x+'').join('')}
hide:
  - toc
---

{% include "_snippets/servicos/titulo.txt" %}

{% include "_snippets/servicos/descricao.txt" %}

{% include "_snippets/servicos/canais.txt" %}

{% include "_snippets/servicos/documentacao.txt" %}

{% include "_snippets/servicos/custo.txt" %}

{% include "_snippets/servicos/prazo.txt" %}

{% include "_snippets/servicos/responsavel.txt" %}

{% include "_snippets/servicos/legislacao.txt" %}

`}

csv = csv.filter(x=> !['site-19','site-21','site-42','site-43','site-77','site-82','site-83','site-95','site-96',
'site-97','site-116','site-195','site-196','site-198','site-199','site-200','site-201'].includes(x["Código Único"]))


var fs = require('fs');
 
// writeFile function with filename, content and callback function
fs.writeFile('newfile.txt', 'Leadule', function (err) {
  if (err) throw err;
  console.log('File is created successfully.');
});


csv.map( x => { fs.writeFile(x['Código Único']+'.md', genheader(x), x=>x) } )
